### PR TITLE
fail on read/write attempts after last sector

### PR DESCRIPTION
**Pull request by sg2342**

### CODE REVIEW

**Comment by talex5** [comment]
Seems like this only checks that the start offset is in range. Shouldn't it include the length of the buffer too? (being careful about integer overflow too, of course)

**Comment by sg2342** [comment]
i will work on it (include the buffer length + add tests) and update the PR

**Comment by sg2342** [comment]
i have updated the pr, please review.

**Comment by talex5** [comment]
This is probably OK, although I am slightly worried about a few points:

- If I change the unit test to pass a start sector of `Int64.max_int` then it doesn't give me End_of_file (although it does fail anyway, since the file can't grow that big).

- The buffer size in sectors gets rounded down, rather than up. Does the test fail if the buffer is shorter than a sector?

- I wonder if we should prevent negative start sectors too.

- Might be nice to factor out the check into a separate function, rather than duplicating it.

However, it's certainly better than what we have now. @djs55, what do you think? (picking on you because the opam file gives you as the maintainer :-) )

**Comment by talex5** [comment]
Might be able to reuse this code: https://github.com/mirage/ocaml-mbr/blob/9d3deac587b8cd6652d1c3806045ad94513e00a0/lib/mbr_partition.ml#L69

**Comment by sg2342** [comment]
* About buffers beeing shorter than a sector: mirage V1.mli states that "Each of [buffers] must be a whole number of sectors in length" for read and write. Whether or not such a statement requires inclusion of relevant assertions in V1.BLOCK implementations is unknown me.

I think, read and write _must_ fail if called with in-spec arguments (positive start sector, list of buffers that are of correct size) that cause access after the last sector (because released client code  -- mirage-skeleton block test -- relies on this).

**Comment by talex5** [comment]
Yes, it's not quite clear, but failing on invalid arguments would be the safe thing to do.

**Comment by hannesm** [comment]
We should be careful to specify which piece checks which bounds, otherwise we end up in multiple or no bounds checks at all. The checks for negative sectors etc. should be done elsewhere, since it should be generic for all block implementation (and thus, we should implement the checks only once).

**Comment by djs55** [comment]
Making the checks generic is a good point -- we now have several implementations of `BLOCK`, most of which are probably broken in the same way :) I've made [mirage/mirage#448] to track the lack of a common place to put these checks. I think perhaps we could write a functor wrapper over `BLOCK` which could be instantiated by the mirage tool's generated boilerplate and which could contain the bounds-checks.

In the mean-time I think it's important for everyday development to have the unit tests pass, so I'm happy to merge this for now as it's certainly better than what we have now, as @talex5 pointed out!

**Pull request merged**
