### PR TITLE
Check file is sector aligned

### PR DESCRIPTION
**Pull request by reynir**
As it is now you can attach to files which are not aligned with the sector size (often 512 bytes), and you only get a warning about this if you connect with `~buffered:false` (not the default). Then mirage-block-unix on read will conjure up zero bytes to make up for the non-existing bytes. My opinion is that it's bad behavior to return bytes that aren't there on the disk.

This change checks in `connect` that the file is sector-aligned, and simplifies the `read` code.

See also https://github.com/Solo5/solo5/pull/527.

### CODE REVIEW

**Comment by dinosaure** [comment]
I think @Julow is probably interesting by this PR when he already did some works about that.

**Comment by hannesm** [comment]
I'm in favour of this. But could you fix the tests so that CI has a chance to pass?

**Comment by reynir** [comment]
It seems to pass now except for the AppVeyor build which fails for unrelated reasons.

While updating the test I thought about creating a new exception rather than using `Failure`. I'm not sure.

**Comment by dinosaure** [comment]
> It seems to pass now except for the AppVeyor build which fails for unrelated reasons.

Yes, we should definitely delete AppVeyor.

**Comment by hannesm** [comment]
Maybe worth to replace AppVeyor by GitHub action (so we don't loose testing on windows)?

**Pull request merged**
